### ISSUE TITLE
All test suites are finalizedBy your reporting task

### ISSUE THREAD

**Issue by Jerbell** [SpacialCircumstances/gradle-cucumber-reporting#1]
Hi,
I'm in a situation where I have a unit test suite, and separate Cucumber test suite.  Unfortunately, by including your plugin, if I want to just run the unit tests, then it will fail as you do a finalizedBy generate cucumber report task.  
As far as I can tell there is no way to clear a finalizedBy after it's been set.  Might be wrong there.
Julian

**Comment by SpacialCircumstances** [comment]
Sorry for being a bit late with anwering, somehow I was not watching this repository...
I have released a new version (0.0.8) that allows skipping report generation by running gradle with the flag `-PskipReports`. I hope that fixes your problem (for now), but I am currently working on adding incremental task generation so reports are only generated when the cucumber reports file changes.

**Comment by SpacialCircumstances** [comment]
Fixed in version 0.0.11 with #2 .
