### ISSUE TITLE
Cucumber Reporting Trends Statistic

### ISSUE THREAD

**Issue by ibnuhhazars** [SpacialCircumstances/gradle-cucumber-reporting#10]
hi , 
i have to run and generate cucumber reporting in jenkins, 
but i can't see trends statistic like this,

https://github.com/damianszczepanik/cucumber-reporting/blob/master/.README/trends.png

anyone know how to configure it ? 

gradle task
`cucumberReports {
    runWithJenkins = true
    outputDir = file("$projectDir/target/generated-reports")
    reports = files("$projectDir/target/cucumber-parallel/json/example-report.json")
}
`

**Comment by SpacialCircumstances** [comment]
Hello,
I've created a new version 0.1.10 that supports trends.
You can specify them in your build.gradle like this:

```
cucumberReports {
    outputDir = file("$projectDir/output/generated-reports")
    buildId = '0'
    reports = files("$projectDir/reports/example-report.json")
    trends = file("$projectDir/reports/trends.json")
}
```
And optionally specify a limit via `trendsLimit`, taking an integer.

I hope this works for you.

**Comment by ibnuhhazars** [comment]
Hi Felix,
Ahhhhhhh Excellent It's Workkkkkkk, Thanks for your response and Solution :)
