### ISSUE TITLE
Skipped scenarios are marked as failed

### ISSUE THREAD

**Issue by KITSIgorPidgurskyi** [SpacialCircumstances/gradle-cucumber-reporting#14]
Background - It's possible to have scenarios which should be run against one configuration, and another - for opposite one. In such case runner should skip those scenarios  which shouldn't be run against current config.

Underlying project https://github.com/damianszczepanik/cucumber-reporting provides such capability by passing additional config line:
configuration.setNotFailingStatuses(Collections.singleton(Status.SKIPPED));

<img width="747" alt="Знімок екрана  о 15 53 47" src="https://user-images.githubusercontent.com/28754396/66570397-2de28900-eb76-11e9-94f6-819da35963f2.png">

Thanks in advance

**Comment by SpacialCircumstances** [comment]
Thank you for reporting this. The configuration option `notFailingStatuses` provides this functionality in the new release.
```
cucumberReports {
    ...
    notFailingStatuses = [ "skipped" ]
}
```
