### ISSUE TITLE
Gradle build fail

### ISSUE THREAD

**Issue by RuslanSinyavsky** [SpacialCircumstances/gradle-cucumber-reporting#16]
Hey,
The plugin needs the Cucumber.json file to execute. I want to build my project, in some cases, without running the cucumber tests (to save time), therefore no Cucumber.json will be generated. However, I will still have the Plugin and Configuration in my build.gradle file, and so when doing "gradle build" in the terminal the generateCucumberReport plugin will execute and fail my build. Is there a way for the plugin to not execute when it does not detect the Cucumber.json and just skip its execution (optional config?)? 
Thank you.

**Comment by SpacialCircumstances** [comment]
Hello,
at the moment, there are two ways to achieve this:

1.  Pass the parameter `-PskipReports` to gradle when running your builds
2. The plugin will automatically attach to all tasks of type `test` via `finalizedBy`. You can deactivate this behaviour by setting `testTasksFinalizedByReport` to `false`, then manually attaching the plugin task to your cucumber task, f.e. `cucumberTests.finalizedBy(generateCucumberReports)`

**Comment by RuslanSinyavsky** [comment]
Great, thanks.
