### ISSUE TITLE
Why my Screenshot attach on hooks ?

### ISSUE THREAD

**Issue by ibnuhhazars** [SpacialCircumstances/gradle-cucumber-reporting#17]
Hi, 

i have different example report screenshot attach
currently i got report like this:
![Screen Shot 2019-10-25 at 15 04 35](https://user-images.githubusercontent.com/47444358/67554765-34f2c500-f73a-11e9-9e80-bb4c1e1ad556.png)

but my expectation like this:
![Screen Shot 2019-10-25 at 15 05 03](https://user-images.githubusercontent.com/47444358/67554836-505dd000-f73a-11e9-9262-ad60ad3d576d.png)

Current After Hook Code 
```
import io.cucumber.core.api.Scenario;

@After
public void after(Scenario scenario) {
      if (scenario.isFailed()) {
        scenario.embed(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES), "image/png");
        scenario.write("Scenario Fail");
      }
}
```

Anyone can explain about this ? 
Thanks :)

**Comment by SpacialCircumstances** [comment]
Hello,
I am unsure how to achieve this with an after hook.
An ugly solution would be to add try/catch handlers to all of your test methods and handle the screen shots there. But most likely, there is a better way and I just can't think of it.

Anyways, this plugin does not directly implement report generation. I would recommend you to file an issue and link to this one at [https://github.com/damianszczepanik/cucumber-reporting](https://github.com/damianszczepanik/cucumber-reporting), which is used by this plugin to generate the HTML reports.

**Comment by ibnuhhazars** [comment]
Hi felix,

Thanks your for response my question and recommend

:)
