### ISSUE TITLE
document the jdk versions used per plugin version

### ISSUE THREAD

**Issue by vincent-fuchs** [SpacialCircumstances/gradle-cucumber-reporting#18]
My project is using JDK 11. When trying to use 

    plugins {
        id "com.github.spacialcircumstances.gradle-cucumber-reporting" version "0.1.16"
    }

I get an error : 

>What went wrong:
>java.lang.UnsupportedClassVersionError: com/github/spacialcircumstances/gradle/ReportsPlugin has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0
> com/github/spacialcircumstances/gradle/ReportsPlugin has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0

I know I could upgrade on my side to JDK 12, but I can't for now because of company policy. 

I looked at the commits quickly, but couldn't find the version from which you started to use JDK 12 to compile and publish the plugin.

Could you add a section in readme indicating from which verison onward of the plugin JDK 12 needs to be used ? This way I could use the version just before for now. 

Thanks !

**Comment by SpacialCircumstances** [comment]
Hello,
this was a mistake on my part. There's no reason to use JDK 12 here, no recent features are used. I simply forgot to switch the JDK version when I built the last release. I've just published a new version (0.1.17) which was built using JDK 8, and I will continue to use JDK 8 until a switch is necessary (and then, I will put a message in the README).
I hope this fixes your issue!

**Comment by vincent-fuchs** [comment]
Thanks for the quick fix !!
