### ISSUE TITLE
Consolidate all reports into one location

### ISSUE THREAD

**Issue by Arc-E-Tect** [SpacialCircumstances/gradle-cucumber-reporting#19]
Hi,

How would I consolidate all reports generated by Cucumber in separate subprojects in a multi-project into one single report?

I have a multi-project with three of the subprojects containing Cucumber features and reports, but they are all in a directory of the subproject. I would like to have a single report available with all reports of the subprojects consolidated.
Thanks.

**Comment by SpacialCircumstances** [comment]
Hello,

the configuration of reports accepts multiple JSON files (to be precise, it takes a gradle FileCollection).
`reports = files('path/to/cucumber-report.json', 'another/cucumber-json.json') `
This way you can specify multiple json report files that are merged into one HTML report. Of course, you can also use wildcards etc., basically everything in gradle that returns a FileCollection.
I hope this works for you!

**Comment by Arc-E-Tect** [comment]
Thanks, I will try that and let you know whether or not I succeeded

**Comment by Arc-E-Tect** [comment]
Wanted to let you know that it works. Thanks again.
