### ISSUE TITLE
How to support ReducingMethod.MERGE_FEATURES_BY_ID?

### ISSUE THREAD

**Issue by MichelleZhou-airwallex** [SpacialCircumstances/gradle-cucumber-reporting#23]
when I run ParallelCucumber by SCENARIO level, the report will not merge the scenarios for the same feature.
I found that the cucumber reporter already support this feature, merge features by ID, so how can I apply this?
thx~

the related issue link: https://github.com/jenkinsci/cucumber-reports-plugin/issues/172

**Comment by SpacialCircumstances** [comment]
I have released a new version that supports configuring the reducing method!

You just need to add:

```
...
reducingMethod("MERGE_FEATURES_BY_ID")
...
```
into the plugin configuration.

I hope this works for you, else, feel free to report back!

**Comment by MichelleZhou-airwallex** [comment]
> I have released a new version that supports configuring the reducing method!
> 
> You just need to add:
> 
> ```
> ...
> reducingMethod("MERGE_FEATURES_BY_ID")
> ...
> ```
> 
> into the plugin configuration.
> 
> I hope this works for you, else, feel free to report back!

cool, it works. thx for the quick upgrade~

```
cucumberReports {
...
reducingMethod(net.masterthought.cucumber.reducers.ReducingMethod.MERGE_FEATURES_BY_ID)
...
}
```
