### ISSUE TITLE
Getting Error while trying to run plugin with AWS Codebuild job

### ISSUE THREAD

**Issue by jcsingh** [SpacialCircumstances/gradle-cucumber-reporting#3]
Issue Description: The plugin works fine when I run the generateCucumberReports task on my local but when the same task is run during AWS Codebuild job then it fails with following error.

Root project name is already set in settings.gradle file 
rootProject.name='someprojectname' 

FAILURE: Build failed with an exception.

* Where:
Build file '/codebuild/output/someprojectname/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.spacialcircumstances.gradle-cucumber-reporting', version: '0.0.11']
> Failed to apply plugin [id 'com.github.spacialcircumstances.gradle-cucumber-reporting']
   > Could not find property 'displayName' on root project 'someprojectname'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by SpacialCircumstances** [comment]
Sadly, I don’t have experience with AWS Codebuild. The error occurrs when the project does not have the property „displayName“. This property is present in Gradle since version 4.0, maybe you are using an older version?

**Comment by jcsingh** [comment]
Thank You for your pointer.
I had gradle 4.7 on my local but the ubuntu instance that code build spins off had gradle version 1.4 by default. Upgrading to gradle 4.7 in buildspec file solved the issue.

**Comment by SpacialCircumstances** [comment]
Great to hear that!

**Comment by ghost** [comment]
@jaspreet-singh-chadha : I am looking for some help in how to run/install cucumber reports plugin from AWSCodeBuild. Let me know if you could help me on this. Thanks!!
