### ISSUE TITLE
damianszczepanik/cucumber-reporting change Configuration class

### ISSUE THREAD

**Issue by demtnt** [SpacialCircumstances/gradle-cucumber-reporting#5]
* What went wrong:
Execution failed for task ':psd2-tests:generateCucumberReports'.
> No signature of method: net.masterthought.cucumber.Configuration.setParallelTesting() is applicable for argument types: (java.lang.Boolean) values: [false]

It is looks like they have removed unused parameter "parallelTesting" at 8th of October.

**Comment by SpacialCircumstances** [comment]
Oh yes. I must have overlooked this.
I´ve published version 0.1.0 (because of the breaking change) that fixes this and also improves some other aspects.

**Comment by demtnt** [comment]
thanks for superfast response. already try new version. 

One more thing: it would be nice to remove from Optional configuration of readme file too.

**Comment by SpacialCircumstances** [comment]
Thank you, I´ve updated the README to reflect the changes in the new version.
