### ISSUE TITLE
Failed to apply plugin

### ISSUE THREAD

**Issue by HesterLyons** [SpacialCircumstances/gradle-cucumber-reporting#6]
When applying the plugin in the build.gradle file, the build returns the following error:
An exception occurred applying plugin request [id: 'com.github.spacialcircumstances.gradle-cucumber-reporting', version: '0.1.2']
> Failed to apply plugin [id 'com.github.spacialcircumstances.gradle-cucumber-reporting']
   > Could not get unknown property 'displayName' for root project 'MyTestProject' of type org.gradle.api.Project.

do you know what might be causing this?

**Comment by SpacialCircumstances** [comment]
The property project.displayName exists since Gradle >= 3.3, so probably you are using a version that is older than that.

**Comment by HesterLyons** [comment]
Thanks. I suspect it was weirder than that, I'm using Gradle 5.0 but had renamed the project manually and I think the display name was different to the package name which is why it got confused. I've now built a clean version of my package and it works fine. Thanks for the quick response.
