### ISSUE TITLE
Gradle build fails when plugin is added

### ISSUE THREAD

**Issue by nikhil6686** [SpacialCircumstances/gradle-cucumber-reporting#9]
Hi,
When I follow instructions in readme and add the plugin, my build command fails with 
No report files found, aborting...
My cucumberTest task gets executed later and I would like to tie this with cucumberTest task. Any way to bypass the plugin during build task?
Thanks,
Nikhil

**Comment by SpacialCircumstances** [comment]
You can avoid the error by adding `testTasksFinalizedByReport = false` to your cucumber reports configuration, so the reports are not generated automatically after running a test. 
Then, you can manually attach them to your cucumber test task via `yourCucumberTestTask.finalizedBy(generateCucumberReports)` so they will only run after cucumber tests.

**Comment by nikhil6686** [comment]
Works like a charm, thanks alot for the tip :)
Nikhil

**Comment by peacetrader** [comment]
Hi, I am having the same issue. I am new to gradle. Could someone help me on how to add these lines in build.gradle?. 
My task looks like this :
`test {
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
    }
    doFirst {
        delete testResultsDir
    }
    useTestNG()
    scanForTestClasses = false
}`

`cucumberReports {
    outputDir = file('html-report')
    buildId = '0'
    reports = files('target/cucumber/cucumber.json')
}`

**Comment by SpacialCircumstances** [comment]
@purnimashanti I'm not exactly sure if I'm understanding you right, but if you're talking about the code snippet commented by me above, your configuration should look like this:

```
cucumberReports { 
    outputDir = file('html-report')
    buildId = '0'
    reports = files('target/cucumber/cucumber.json')
    testTasksFinalizedByReport = false
}
```

**Comment by peacetrader** [comment]
I am not sure how to use this `yourCucumberTestTask.finalizedBy(generateCucumberReports)`
Do I have to specify it like this : 
`test {
    useTestNG()
    scanForTestClasses = false
}

test.finalizedBy(generateCucumberReports)`

**Comment by SpacialCircumstances** [comment]
@purnimashanti Yes, that would be the correct way, causing the reports to be generated after the tests are run.

**Comment by peacetrader** [comment]
Hi, I still have the same issue. I am running gradle clean build. 

18:28:42 > Task :compileTestJava
18:28:42 Note: /home/jenkins-slave/workspace/Nrem API tests/src/test/java/com/thales/library/common/ExcelLibrary.java uses unchecked or unsafe operations.
18:28:42 Note: Recompile with -Xlint:unchecked for details.
18:28:42 
18:28:42 > Task :processTestResources
18:28:42 > Task :testClasses
18:28:44 > Task :test
18:28:44 
18:28:44 > Task :generateCucumberReports FAILED
18:28:44 Reports file /home/jenkins-slave/workspace/Nrem API tests/target/cucumber/jsonreports/cucumber.json not found
18:28:44 No report files found, aborting...
18:28:44 
18:28:44 FAILURE: Build failed with an exception.
18:28:44 
18:28:44 * What went wrong:
18:28:44 Execution failed for task ':generateCucumberReports'.
18:28:44 > No test files found
18:28:44 
18:28:44 * Try:
18:28:44 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
18:28:44 
18:28:44 * Get more help at https://help.gradle.org

**Comment by SpacialCircumstances** [comment]
@purnimashanti Well, have you checked if there is actually a cucumber report file `target/cucumber/cucumber.json`? That's a somewhat uncommon path, because `target/` is usually used by Maven, while Gradle uses `build/` to store such files.

**Comment by peacetrader** [comment]
Hi, I changed the path to target/cucumber/cucumber.json and it's working. Thanks.
